# Generated by Django 5.1.1 on 2024-10-07 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_sortie',
            field=models.DateField(default=datetime.date(2024, 10, 7)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 10, 7)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 10, 7)),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='date_creation',
            field=models.DateField(default=datetime.date(2024, 10, 7)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom_utilisateur',
            field=models.CharField(),
        ),
    ]
