# Generated by Django 5.1.1 on 2024-10-09 15:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0002_alter_album_date_sortie_alter_concert_date_debut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='adresse_mail',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='mdp',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_sortie',
            field=models.DateField(default=datetime.date(2024, 10, 9)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 10, 9)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 10, 9)),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='date_creation',
            field=models.DateField(default=datetime.date(2024, 10, 9)),
        ),
    ]
