# Generated by Django 4.2.16 on 2024-11-13 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0003_remove_utilisateur_adresse_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('prenom', models.CharField()),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='lieux',
            new_name='lieu',
        ),
        migrations.AddField(
            model_name='concert',
            name='intitule',
            field=models.CharField(default=datetime.datetime(2024, 11, 13, 17, 27, 9, 255055, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='date_sortie',
            field=models.DateField(default=datetime.date(2024, 11, 13)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 11, 13)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_rest_babord.groupe'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 11, 13)),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='date_creation',
            field=models.DateField(default=datetime.date(2024, 11, 13)),
        ),
    ]
