# Generated by Django 4.2.16 on 2024-11-19 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0004_utilisateurmobile_rename_lieux_concert_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_sortie',
            field=models.DateField(default=datetime.date(2024, 11, 19)),
        ),
        migrations.AlterField(
            model_name='album',
            name='lieux',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 11, 19)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='lieu',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 11, 19)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='lieux',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='date_creation',
            field=models.DateField(default=datetime.date(2024, 11, 19)),
        ),
        migrations.DeleteModel(
            name='Lieu',
        ),
    ]
