# Generated by Django 4.2.16 on 2024-11-20 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0005_alter_album_date_sortie_alter_album_lieux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom_utilisateur',
        ),
        migrations.AlterField(
            model_name='album',
            name='date_sortie',
            field=models.DateField(default=datetime.date(2024, 11, 20)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 11, 20)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date_debut',
            field=models.DateField(default=datetime.date(2024, 11, 20)),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nb_femme',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nb_homme',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
