# Generated by Django 4.2.16 on 2024-11-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0006_remove_utilisateur_nom_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='groupe',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='groupe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest_babord.groupe'),
        ),
    ]
