# Generated by Django 4.2.16 on 2024-12-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0011_alter_album_date_sortie_alter_concert_date_debut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festival',
            old_name='lieux',
            new_name='lieu',
        ),
    ]
