# Generated by Django 4.2.16 on 2024-12-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0012_rename_lieux_festival_lieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='lieux',
            new_name='lieu',
        ),
    ]
