# Generated by Django 4.2.16 on 2024-12-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0013_rename_lieux_album_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='valider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concert',
            name='valider',
            field=models.BooleanField(default=False),
        ),
    ]
