# Generated by Django 4.2.16 on 2025-01-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0018_remove_groupe_date_creation_groupe_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='producteur',
            field=models.CharField(blank=True, null=True),
        ),
    ]
