# Generated by Django 4.2.16 on 2025-01-12 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0019_alter_groupe_producteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_sortie',
            field=models.DateField(default=datetime.date(2025, 1, 12)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date_debut',
            field=models.DateField(default=datetime.date(2025, 1, 12)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date_debut',
            field=models.DateField(default=datetime.date(2025, 1, 12)),
        ),
        migrations.AlterField(
            model_name='utilisateurmobile',
            name='suivre_groupe',
            field=models.ManyToManyField(blank=True, to='api_rest_babord.groupe'),
        ),
    ]
