# Generated by Django 4.2.16 on 2025-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0020_alter_album_date_sortie_alter_concert_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurmobile',
            name='suivre_groupe',
            field=models.ManyToManyField(to='api_rest_babord.groupe'),
        ),
    ]
