# Generated by Django 4.2.16 on 2025-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0021_alter_utilisateurmobile_suivre_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurmobile',
            name='suivre_groupe',
            field=models.ManyToManyField(blank=True, to='api_rest_babord.groupe'),
        ),
    ]
