# Generated by Django 4.2.16 on 2025-01-14 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0022_alter_utilisateurmobile_suivre_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_sortie',
            field=models.DateField(default=datetime.datetime(2025, 1, 14, 13, 37, 33, 420209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2025, 1, 14, 13, 37, 33, 420482, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2025, 1, 14, 13, 37, 33, 420717, tzinfo=datetime.timezone.utc)),
        ),
    ]
