# Generated by Django 4.2.16 on 2025-01-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0024_alter_album_date_sortie_alter_concert_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='lien_facebook',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='lien_instagram',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='lien_site',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='lien_twitter',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='lien_youtube',
            field=models.CharField(blank=True, null=True),
        ),
    ]
