# Generated by Django 4.2.16 on 2025-01-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0025_groupe_lien_facebook_groupe_lien_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='api_rest_babord.groupe'),
        ),
    ]
