# Generated by Django 4.2.16 on 2025-01-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0026_alter_album_groupe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['libelle']},
        ),
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['intitule']},
        ),
        migrations.AlterModelOptions(
            name='festival',
            options={'ordering': ['date_debut']},
        ),
        migrations.AlterModelOptions(
            name='groupe',
            options={'ordering': ['libelle']},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['titre']},
        ),
    ]
