# Generated by Django 4.2.16 on 2025-01-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_babord', '0027_alter_album_options_alter_concert_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurmobile',
            name='ville',
        ),
    ]
